### ISSUE TITLE
Duplicates asked

### ISSUE THREAD

**Issue by WiseWomanVP** [Auregann/derdiedas#2]
There are a lot of duplicates returned. You check for these by keeping track of the past ones and when selecting a new one, first checking if it is in the list.

initialize array a, i=-1 // assuming array starts at 0
score = 0
while (i < 9)
     w = generate new random lexeme number
     alreadyChosen = false
     for (int j=0; j<i; j++)
         if (a[j] == w) alreadyChosen = true
     if (not alreadyChosen)
        a[++i] = w
        score = score + resultOfGuessing(w)
postFinalScore (score)

Sorry, I don't do JavaScript, so I have this in pseudocode :)

**Comment by Auregann** [comment]
I decided to partially keep the duplicates, because I think it's part of the learning process to have several times the same word, until one learns it. However, I changed the code so the same lemma doesn't appear twice in a row.
Thanks a lot for your helpful comment :)
