### ISSUE TITLE
Same endings

### ISSUE THREAD

**Issue by WiseWomanVP** [Auregann/derdiedas#3]
There are a lot of words that end in -in which are obvious, and many that are in a similar class (Fahrrad, Zweirad, Dreirad). This is a bit more work, but you could check not only if the word already exists, but keep track of the last 3-5 letters of each lexeme presented and if your newly chosen one matches one already in the game, then choose a new one.

**Comment by Auregann** [comment]
Hello,
I've been thinking about this, but I will not add the feature for now. I actually think it's helpful for learning, when you learn the article for the noun "rad" you can apply it to other nouns, and it helps understanding how the language works.
Thanks for reporting anyway :)
