### ISSUE TITLE
list of previous responses and footer overlap

### ISSUE THREAD

**Issue by maxlath** [Auregann/derdiedas#4]
![selection_002](https://user-images.githubusercontent.com/1596934/47731810-2d9ef580-dc65-11e8-8fb7-6efc9700d34a.png)

This could easily be fixed by setting a bigger `margin-bottom` on the `Previously` section and a `background-color: white` on `#footer` to avoid seeing the text through the footer

**Comment by Auregann** [comment]
Should now be fixed :)
